#ifndef CONSTANTS_H
#define CONSTANTS_H

#define SCREEN_HEIGHT 800
#define SCREEN_WIDTH 800
#define SCREEN_CENTER (Vector2){SCREEN_WIDTH/2, SCREEN_HEIGHT/2}
#define SCREEN_RECT (Rectangle) {0,0,SCREEN_WIDTH, SCREEN_HEIGHT}

#define NEARBLACK (Color) { 30, 30, 30, 255 }

#define MAX_ASTEROIDS 64
#define ASTEROID_RANDOM_ANGLE 20 * DEG2RAD


#endif